### ISSUE TITLE
Allow author to limit number of horizontal lines

### ISSUE THREAD

**Issue by ChristopherChudzicki** [SketchResponse/sketchresponse#10]
The horizontal line module is frequently used for horizontal asymptotes.  I do not think a student should ever draw more than two horizontal asymptotes for one function, and frequently only one is needed. 

It might be good to allow authors to limit the number of horizontal asymptotes that can be drawn. For example:

```
{'name': 'horizontal-line', 'id': 'ha', 'label': 'Horizontal asymptote', 'max-num':2},
```

I've been thinking of using the `horizontal-line` tool to allow students to mark the total energy in a potential-energy plot. That's another situation where we would only ever want one single horizontal line.

**Comment by brian-french** [comment]
We discussed this and decided not to add this feature. It is already something you can constrain through the grader script.
