### ISSUE TITLE
Broken link in complex grader docs

### ISSUE THREAD

**Issue by msegado** [SketchResponse/sketchresponse#11]
There's a mis-formatted link on http://sketchresponse.github.io/complex_grader.html:

> The 'axes' and 'freeform' plugin usage here is identical to the Simple Grader Tutorial and is explained there as well as on the **_[Plugin Description Page(probconfig_plugins.md)._**

**Comment by brian-french** [comment]
Fixed. Will be resolved when the new docs are built after merging JMs branch.
