### ISSUE TITLE
Checking for existence, inconsistence grader behavior

### ISSUE THREAD

**Issue by ChristopherChudzicki** [SketchResponse/sketchresponse#4]
There seems to be some inconsistency in whether the `GradeableFunction` grading functions check for existence.  In particular, `f.is_straight_between` does not check for existence but `f.has_negative_curvature_between` does. 

Is this intended? I would have expected both functions to check for existence.

```
@sketchresponse.grader
def grader(f):
    f = GradeableFunction.GradeableFunction(f)

    #This DOES NOT check for existence
    if not f.is_straight_between(0, 4):
        return False, 'Should be straight'
    #This DOES check for existence
    if not f.has_negative_curvature_between(4, 8):
        return False, 'Should be concave down'

    return True, 'Good Job'
```

Thus:
<img width="350" alt="screen shot 2016-06-29 at 9 07 32 am" src="https://cloud.githubusercontent.com/assets/9010790/16453161/db358510-3dd9-11e6-9528-ddaa312e949c.png">
<img width="350" alt="screen shot 2016-06-29 at 9 07 58 am" src="https://cloud.githubusercontent.com/assets/9010790/16453163/db4e5dc4-3dd9-11e6-8e0a-fcd8ca543e41.png">
<img width="350" alt="screen shot 2016-06-29 at 9 08 24 am" src="https://cloud.githubusercontent.com/assets/9010790/16453162/db4b0444-3dd9-11e6-9b13-73220fc303f7.png">

**Comment by brian-french** [comment]
Fixed. Added explicit test for existence to a few grader functions that didn't look like they were capturing that already.
