### ISSUE TITLE
Grader Issue: PolyLine does not work with GradeableFunction

### ISSUE THREAD

**Issue by ChristopherChudzicki** [SketchResponse/sketchresponse#43]
This morning I was writing a problem for 18.03L in which we wanted to use the `polyline` tool for drawing a piecewise linear function.

**Bug:** `polyline` seems not to work with GradeableFunction. I believe this is a bug. If it is by design, then it would be great to have `polyline` be able to instantiate GradeableFunction instances.

To reproduce:
1. Run grader script below
2. Draw something with poly line tool (Something must be drawn to see issue)
3. Hit grade

```python
import sketchresponse
from grader_lib import GradeableFunction, PolyLine, LineSegment

problemconfig = sketchresponse.config({
    'width': 750,
    'height': 420,
    'xrange': [-1.2, 5.2],
    'yrange': [-2.5, 2.5],
    'xscale': 'linear',
    'yscale': 'linear',
    'plugins': [
        {'name': 'axes'},
        {'name': 'polyline', 'id': 'line', 'label': 'Line Tool', 'color': 'blue', 'size': 15},
    ]
})

@sketchresponse.grader
def grader(line):
    f = GradeableFunction.GradeableFunction(line)
    return True, "Message"
```

Edit: Traceback ends in:
```
/sketchresponse/grader_lib/SplineFunction.py", line 21, in __init__
    self.domain = [self.functions[0].p0[0], self.functions[-1].p3[0]]
```

I guess it makes sense that `SplineFunction` is expecting at least four points.

**Comment by ChristopherChudzicki** [comment]
@jefrench This is what was causing the bug in your skyscraper function script

**Comment by brian-french** [comment]
You cannot interact with polylines directly with gradeablefunction because the data format is incompatible. You have to instantiate it with the polyline grader and from there you can interact with the polyline data as either a set of line segments or as splines with the gradefunction grader.

**Comment by ChristopherChudzicki** [comment]
@brian-french Thanks for the reply. I did find `PolyLines. get_polyline_as_splines(index)` in the documentation. This would work, except I'm having trouble with `index`.  

For 18.03L, we want to use `polyline` to draw piecewise linear functions and so we want to grade them as if they were `freeform`. But it seems to me that `get_polyline_as_splines` causes trouble for many grading methods (`does_exist_between` and `has_constant_value_y_betwee` to name a few). For example:

![bug_report2](https://user-images.githubusercontent.com/9010790/27809617-4b94808c-601f-11e7-9564-03c1c4d5503e.png)

The problem is that with freeform, both pieces are treated as part of the same `GradeableFunction`.  But with `get_polyline_as_splines(index)` only a single piece is part of the GradeableFunction.

Am I missing something? Is there a way I can robustly check for existence using `polyline` tool?

**Comment by brian-french** [comment]
That is a good point. I must admit I designed the polyline module without a lot of examples of how it was going to be used. It may be feasible to just treat all the polyline data as a single function instead of handling each polyline instance separately. It would also simplify the the polyline api, making it behave more like all the other modules.

**Comment by ChristopherChudzicki** [comment]
> It may be feasible to just treat all the polyline data as a single function instead of handling each polyline instance separately. It would also simplify the the polyline api, making it behave more like all the other modules

That is the behavior I was expecting since, as you say, it would be more like grader APIs. But the only use-case I've really thought about is piecewise linear functions.

@msegado @jefrench What do you think?

**Comment by jefrench** [comment]
I agree. @brian-french  can you modify it so that it behaves more like other data? That would be ideal.

**Comment by brian-french** [comment]
Done. The polyline grader now collapses all polylines into a single list of splines with one spline per segment of a polyline. It then builds a linesegments grader and a gradeablefunction grader that you can get through the polyline object.

Let me know if this behaves more like what you were expecting.

**Comment by ChristopherChudzicki** [comment]
@brian-french This is great! Works just like I was imagining, except in one respect: if the PolyLine is empty, then `get_polyline_as_gradeablefunction` returns None when I would expect an empty GradeableFunction.

Here's an example:

```python
import sketchresponse
from grader_lib import GradeableFunction, PolyLine

problemconfig = sketchresponse.config({
    'plugins': [
        {'name': 'axes'},
        {'name': 'polyline', 'id': 'f', 'label': 'polyline', 'color': 'blue', 'size': 15},
        {'name':'freeform','id':'g','label':'freeform','color':'red'},
    ]
})

@sketchresponse.grader
def grader(f, g):
    f = PolyLine.PolyLines(f).get_polyline_as_gradeablefunction()
    g = GradeableFunction.GradeableFunction(g)

    ##################################################
    # If nothing is drawn, then :
    print( f.does_exist_between(1,4) ) # ERROR!, b/c None has no attribute does_exist_between
    print( g.does_exist_between(1,4) ) # False
    ##################################################
    
    return True, ""
```

Basically, in the above example I would expect that `f` and `g` behave exactly the same in all cases, not just when something has been drawn.

**Comment by brian-french** [comment]
Fixed. Sorry about that, not sure why I did that in the first place. I think that covers it and am closing this issue. Thanks.
