### ISSUE TITLE
Customizable thresholds for `get_point_at` and `has_point_at`

### ISSUE THREAD

**Issue by ChristopherChudzicki** [SketchResponse/sketchresponse#8]
Most grading functions use have optional keyword arguments that can be used to set grading tolerances. Two exceptions are the functions [ `get_point_at(point=False, x=False, y=False)`](https://github.com/SketchResponse/sketchresponse/blob/bf99ec67124070679b4a7950c3d4844012f93e65/grader_lib/GradeableFunction.py#L85) and [`has_point_at(**kwargs)`](https://github.com/SketchResponse/sketchresponse/blob/bf99ec67124070679b4a7950c3d4844012f93e65/grader_lib/GradeableFunction.py#L118). 

I wrote a problem last week where I wanted slightly higher tolerances for these grading functions because the user is placing points on a pre-drawn curve.

 For a particular `GradeableFunction` object, I can edit the tolerances in `self.tolerances`, but this is not very convenient.  (For example, if I edit `self.tolerances['point_distance']`, then I need to make sure `self.tolerances['point_distance_squared']` is matched appropriately.)

It would be great if these grading functions also accepted keyword arguments for setting thresholds!

**Comment by brian-french** [comment]
Fixed in bfrench-tolerances patch
